#!/bin/bash

#SBATCH --nodes 1
#SBATCH --cpus-per-task=32
#SBATCH --output=slurm/outputs/synth_noci

cd $SLURM_SUBMIT_DIR

echo "Running job $SLURM_JOBID\n"

source setup.sh

srun python3 python_scripts/run_synth_NoCI.py --sim_cycles 2147483646 --inj_start 0.01 --inj_end 0.15 --inj_step 0.01 --mixedfreq_only