#!/bin/bash
#SBATCH --nodes 1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=45GB
#SBATCH --output=slurm/outputs/parsec_noci/freqmine_cmesh_x_noci_500m_18GHz_500kB_mar20.out
cd $SLURM_SUBMIT_DIR
source setup.sh
./build/X86/gem5.fast -d ./parsec_results/parsec_noci_largemem_18GHz_500kB/500m/freqmine/cmesh_x_noci/ configs/auto_top/auto_top_fs.py -I 500000000 --benchmark_parsec freqmine -r 1 --checkpoint-dir ./parsec_checkpoints/largemem/freqmine --router_map_file configs/topologies/paper_solutions/cmesh_x_noci.map --flat_vn_map_file configs/topologies/vn_maps/cmesh_x_noci_naive_hops.vn --flat_nr_map_file configs/topologies/nr_list/cmesh_x_noci_naive.nrl --topology FS_NoCI_EscapeVirtualNetworks --noi_routers 20 --noc_clk 1.8GHz --sys-clock 1.8GHz --ruby-clock 1.8GHz --noi_clk 3.6GHz --num-cpus 64 --mem_or_coh mem --num-dirs 16 --num-l2caches 64 --l2_size 500kB --num_chiplets 4 --mem-size 32GB --caches --ruby --network garnet --kernel parsec_disk_image/vmlinux-4.4.186 --disk-image parsec_disk_image/x86-parsec --cpu-type X86O3CPU --restore-with-cpu X86O3CPU --routing-algorithm 2 --use_escape_vns --vcs-per-vnet 10 --evn_deadlock_partition 1 --evn_n_deadlock_free 1 --evn_min_n_deadlock_free 9
